#include<iostream>
using namespace std;
main(){ 
int one;
cout<<"number 1"<<endl;
cin>>one;
int two;
cout<<"number 2"<<endl;
cin>>two;
int three;
cout<<"number 3"<<endl;
cin>>three;
int four;
cout<<"number 4"<<endl;
cin>>four;
int five;
cout<<"number 5"<<endl;
cin>>five;
int six;
cout<<"number 6"<<endl;
cin>>six;
int seven;
cout<<"number 7"<<endl;
cin>>seven;
int eight;
cout<<"number 8"<<endl;
cin>>eight;
int nine;
cout<<"number 9"<<endl;
cin>>nine;
int ten;
cout<<"number 10"<<endl;
cin>>ten;
int eleven;
cout<<"number 11"<<endl;
cin>>eleven;
int twelve;
cout<<"number 12"<<endl;
cin>>twelve;
int thirteen;
cout<<"number 13"<<endl;
cin>>thirteen;
int fourteen;
cout<<"number 14"<<endl;
cin>>fourteen;
int fifteen;
cout<<"number 15"<<endl;
cin>>fifteen;
int add;
add=(one+two+three+four+five);
int multiply;
multiply=(six*seven*eight*nine*ten);
int subtraction;
subtraction=(eleven-twelve-thirteen-fourteen-fifteen);
int addmultiply;
addmultiply=add+multiply;
int final;
final=addmultiply-subtraction;
cout<<"the final result is"<<final<<endl;
}
